### ISSUE TITLE
rake device で ApplicationVerificationFailed

### ISSUE THREAD

**Issue by naoya** [naoya/HBFav2#137]
```
log: sending install command
log: progress report: 5% status: CreatingStagingDirectory
log: progress report: 15% status: ExtractingPackage
log: progress report: 20% status: InspectingPackage
log: progress report: 20% status: TakingInstallLock
log: progress report: 30% status: PreflightingApplication
log: progress report: 30% status: InstallingEmbeddedProfile
log: progress report: 40% status: VerifyingApplication
error: ApplicationVerificationFailed
rake aborted!
Command failed with status (1): [XCODE_DIR="/Applications/Xcode.app/Content...]
/Users/naoya/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/file_utils.rb:54:in `block in create_shell_runner'
/Users/naoya/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/file_utils.rb:45:in `call'
/Users/naoya/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/file_utils.rb:45:in `sh'
/Users/naoya/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/file_utils_ext.rb:37:in `sh'
/Library/RubyMotion/lib/motion/project/template/ios.rb:288:in `block in <top (required)>'
/Users/naoya/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:240:in `call'
/Users/naoya/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:240:in `block in execute'
/Users/naoya/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:235:in `each'
/Users/naoya/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:235:in `execute'
/Users/naoya/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/naoya/.rbenv/versions/2.1.3/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/Users/naoya/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/naoya/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:165:in `invoke'
/Users/naoya/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:150:in `invoke_task'
/Users/naoya/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/naoya/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `each'
/Users/naoya/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `block in top_level'
/Users/naoya/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:115:in `run_with_threads'
/Users/naoya/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:100:in `top_level'
/Users/naoya/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:78:in `block in run'
/Users/naoya/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/naoya/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:75:in `run'
/Users/naoya/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/rake-10.3.2/bin/rake:33:in `<top (required)>'
/Users/naoya/.rbenv/versions/2.1.3/bin/rake:23:in `load'
/Users/naoya/.rbenv/versions/2.1.3/bin/rake:23:in `<main>'
Tasks: TOP => device
```

**Comment by naoya** [comment]
証明書とかなんかおかしいのかな

**Comment by naoya** [comment]
mobileprovision 入れ替えてみたけど収束せず･･･ううむ

**Comment by naoya** [comment]
http://rubymotiondispatch.com/issues/2015/issue-52/

> Application Verification Failed might simply mean the app identifier differs from the one in the provisioning profile.

とあるけど、そんなところ全くいじってないんだけどな

**Comment by Watson1978** [comment]
おおぅ。なんでしょう。
Xcodeで新規に適当なプロジェクトを作りビルドしたアプリを実機で実行できます？
Xcodeが良い感じにプロビジョニング周りを解決してくれると思われます。

**Comment by naoya** [comment]
なるほど。yak shaving の結果 iOS 端末のアップデート中ｗ
終わったら試してみます

**Comment by Watson1978** [comment]
Xcodeで実機で実行できた際に使われていたプロビジョニングを指定していただければ、
転送できるかと思います( ˘ω˘)

**Comment by naoya** [comment]
いけました。iPhone Developer の方の証明書の新しいのを keychaiin に入れてなかったです。
Xcode が勝手に解決してくれた

**Comment by Watson1978** [comment]
Awesome :+1:
